---
title: "Debugging step: Verify installations for LSF"
author: "Antonia Chroni for SJCRH DNB_BINF_Core"
papersize: a4
fontsize: 11pt
links-as-notes: true
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_folding: hide
    toc_depth: 2
    highlight: tango
    number_sections: TRUE
  pdf_document:
    toc: TRUE
    highlight: tango
    number_sections: TRUE
    latex_engine: lualatex
    keep_tex: FALSE
    fig_caption: yes
    fig_crop: no
    fig_height: 2
    fig_width: 3
    toc_depth: 2
always_allow_html: TRUE
urlcolor: blue
linkcolor: black
citecolor: blue
geometry: margin=1in
header-includes: 
  - \usepackage{titling}
  - \usepackage{fancyhdr}
  - \usepackage{graphicx}
  - \usepackage{float}
---

# Set up
```{r load-library, echo=TRUE}
suppressPackageStartupMessages({
  # 01A_run_seurat_qc.Rmd
  library(future)
  library(cowplot)
  library(devtools)
  library(forcats)
  library(GGally)
  library(stringr)
  library(ggpmisc)
  library(ggrepel)
  library(miQC) 
  library(flexmix) # to estimate mixtureModel for miQC
  library(scater) 
  library(Seurat) 
  library(SingleCellExperiment)
  library(irlba) # this solves the issue with RunUMAP code chunk
  library(scooter)
  library(tidyverse)
  library(fs) #file system
  library(RColorBrewer)
  
  # 02_run_SoupX.Rmd
  library(future)
  library(knitr)
  library(SoupX)
  library(Seurat)
  library(stringr)
  library(tidyverse)
  library(tinytex)
  library(hdf5r)

  # 03_run_scDblFinder.Rmd
  library(scDblFinder)
  library(Seurat)
  library(scater)
  library(future)
  library(tidyverse)
  library(grid)
  library(knitr)

  # 04_run_filter_object.Rmd
  library(devtools)
  library(future)
  library(Seurat)
  library(patchwork)
  library(tidyverse)
  library(ggthemes)
  library(scooter)
  library(RColorBrewer)
  library(knitr)

  # 05_run_summary_report.Rmd
  library(tidyverse)  
  library(knitr)
  library(patchwork)

  # 01-integrative-analysis.Rmd
  library(future)
  library(tidyverse)
  library(patchwork)
  library(Seurat)
  library(SeuratObject)
  library(harmony)
  library(rliger)
  library(RcppPlanc)
  library(SeuratWrappers)
  library(scooter)
  library(reshape2)
  library(RColorBrewer)
  library(knitr)
  
  # run-cell-types-annotation.R
  library(yaml)
  library(tidyverse)
  library(celldex)
  
  # 01-cell-types-annotation-SingleR-broad.Rmd
  library(tidyverse)
  library(Seurat)
  library(SingleR)
  library(scooter)
  library(knitr)

  
  library(ShinyCell)
  library(shinyhelper)
  library(DT)
  library(ggdendro)
  })
```

```{r echo=FALSE, warning=FALSE}
opts_chunk$set(fig.align='center',
               external=TRUE,
               echo=FALSE,
               warning=FALSE,
               fig.pos='H')
a4width <- 8.3
a4height <- 11.7
```

# Session Info

```{r echo=FALSE}
sessionInfo()
```
