#!/bin/bash

set -e
set -o pipefail

########################################################################
# Set up running directory
cd "$(dirname "${BASH_SOURCE[0]}")" 

########################################################################
# Read multiple values and assign them to variables by parsing yaml file
cellranger_parameters=$(cat ../../project_parameters.Config.yaml | grep 'cellranger_parameters:' | awk '{print $2}')
cellranger_parameters=${cellranger_parameters//\"/}  # Removes all double quotes
echo "$cellranger_parameters"  # Output: This is a string with quotes.

genome_name_cellranger=$(cat ../../project_parameters.Config.yaml | grep 'genome_name_cellranger:' | awk '{print $2}')
genome_name_cellranger=${genome_name_cellranger//\"/}  # Removes all double quotes
echo "$genome_name_cellranger"  # Output: This is a string with quotes.

########################################################################
# Read root path
#rootdir=$(realpath "./../..")
#echo "$rootdir"

########################################################################
# Create directories to save output files to
mkdir -p ./results/03_cellranger_count_summary

########################################################################
# Run to summarize results generated by CellRanger for all libraries
python3 ./util/summarize_cellranger_results.py --dir=./results/02_cellranger_count/${cellranger_parameters} \
                                              --outdir=./results/03_cellranger_count_summary/
                                              #--genome ${genome_name_cellranger}