#!/bin/bash

set -e
set -o pipefail

########################################################################
# Load modules
module load python/3.9.9

########################################################################
# Set up running directory
cd "$(dirname "${BASH_SOURCE[0]}")" 

########################################################################
# Read multiple values and assign them to variables by parsing yaml file
cellranger_parameters=$(cat ../../project_parameters.Config.yaml | grep 'cellranger_parameters:' | awk '{print $2}')
cellranger_parameters=${cellranger_parameters//\"/}  # Removes all double quotes
echo "$cellranger_parameters"  # Output: This is a string with quotes.

genome_name=$(cat ../../project_parameters.Config.yaml | grep 'genome_name:' | awk '{print $2}')
genome_name=${genome_name//\"/}  # Removes all double quotes
echo "$genome_name"  # Output: This is a string with quotes.

########################################################################
# Create directories to save output files to
mkdir -p ./results/03_cellranger_count_summary

########################################################################
# Run to summarize results generated by CellRanger for all libraries
python ./util/summarize_cellranger_results.py --dir=./results/02_cellranger_count/${cellranger_parameters} \
                                              --outdir=./results/03_cellranger_count_summary/ \
                                              --genome ${genome_name}