##################################################################################################################
# https://kharchenkolab.github.io/numbat/articles/numbat.html
# This will produce a file named 
# {sample}_allele_counts.tsv.gz 
# under the specified output directory, which contains cell-level phased allele counts.
# df_allele_ATC2, # allele dataframe generated by pileup_and_phase script
# https://benwhalley.github.io/just-enough-r/multiple-raw-data-files.html
##################################################################################################################
# Load library
suppressPackageStartupMessages({
  library(Seurat)
  library(readr)
  library(yaml)
  library(tidyverse)
})

#################################################################################
# load config file
configFile <- paste0("../../project_parameters.Config.yaml")
if (!file.exists(configFile)){
  cat("\n Error: configuration file not found:", configFile)
  stop("Exit...")}

# read `yaml` file defining the `params` of the project and strategy analysis
yaml <- read_yaml(configFile)

#################################################################################
# Set up directories and paths to file Inputs/Outputs
root_dir <- yaml$root_dir
metadata_dir <- yaml$metadata_dir
assay <- yaml$assay_annotation_module
analysis_dir <- file.path(root_dir, "analyses", "clone-phylogeny-analysis") 
module_results_dir <- file.path(analysis_dir, paste0("results"))
input_dir <- file.path(module_results_dir, "03-create-pileup-and-phase") 

# Input files
input_file <- c(dir(path = input_dir,  pattern = "_allele_counts.tsv.gz", full.names = TRUE, recursive = TRUE))

# Create step_results_dir
step_results_dir <- 
  file.path(module_results_dir, paste0("04-create-df-allele-rda"))
if (!dir.exists(step_results_dir)) {
  dir.create(step_results_dir)
}

#######################################################
# Create list 
df_allele_list <- list()

for (i in seq_along(input_file)) {
  
  sample_name <- gsub("Create-", "", str_split_fixed(input_file[i], "/", 16)[,15])
  print(sample_name)
  
  # Create results_dir per sample
  results_dir <- file.path(step_results_dir, sample_name)
  if (!dir.exists(results_dir)) {
    dir.create(results_dir)}
  
  # Read data per sample
  cat(sample_name, "Processing...", "\n")
  
  # Read the file
  df_allele_list[[i]] <- read_tsv(input_file[i]) # Use double brackets to assign to the list

  # Save the count matrix
  saveRDS(df_allele_list[[i]], file = paste0(results_dir, "/", "df_allele.rda"))
}

