##################################################################################################################
# https://kharchenkolab.github.io/numbat/articles/numbat.html
# This will produce a file named 
# {sample}_allele_counts.tsv.gz 
# under the specified output directory, which contains cell-level phased allele counts.
# df_allele_ATC2, # allele dataframe generated by pileup_and_phase script
# https://benwhalley.github.io/just-enough-r/multiple-raw-data-files.html
##################################################################################################################
# Load library
suppressPackageStartupMessages({
  library(Seurat)
  library(readr)
  library(yaml)
  library(tidyverse)
})

#################################################################################
# load config file
configFile <- paste0("../../project_parameters.Config.yaml")
if (!file.exists(configFile)){
  cat("\n Error: configuration file not found:", configFile)
  stop("Exit...")}

# read `yaml` file defining the `params` of the project and strategy analysis
yaml <- read_yaml(configFile)

#################################################################################
# Set up directories and paths to file Inputs/Outputs
root_dir <- yaml$root_dir
metadata_dir <- yaml$metadata_dir
assay <- yaml$assay_annotation_module
analysis_dir <- file.path(root_dir, "analyses", "clone-phylogeny-analysis") 
module_results_dir <- file.path(analysis_dir, paste0("results"))
input_dir <- file.path(module_results_dir, "02-create-pileup-and-phase") 

# Input files
input_file <- c(dir(path = input_dir,  pattern = "_allele_counts.tsv.gz", full.names = TRUE, recursive = TRUE))

# Create step_results_dir
step_results_dir <- 
  file.path(module_results_dir, paste0("03-create-df-allele-rda"))
if (!dir.exists(step_results_dir)) {
  dir.create(step_results_dir)
}

#######################################################
# Read metadata file and define `sample_name`
#metadata_file <- file.path(metadata_dir, "project_metadata.tsv") # metadata input file

# Read metadata file and define `sample_name`
#project_metadata <- read.csv(metadata_file, sep = "\t", header = TRUE)
#sample_name <- unique(as.character(project_metadata$ID))
#sample_name <- sort(sample_name, decreasing = FALSE)
#print(sample_name)

#######################################################
# Create list 
df_allele_list <- list()

for (i in seq_along(input_file)) {
  
  sample_name <- gsub("Create-", "", str_split_fixed(input_file[i], "/", 16)[,15])
  print(sample_name)
  
  # Create results_dir per sample
  results_dir <- file.path(step_results_dir, sample_name)
  if (!dir.exists(results_dir)) {
    dir.create(results_dir)}
  
  # Read data per sample
  cat(sample_name, "Processing...", "\n")
  
  # Read the file
  df_allele_list[[i]] <- read_tsv(input_file[i]) # Use double brackets to assign to the list

  # Save the count matrix
  saveRDS(df_allele_list[[i]], file = paste0(results_dir, "/", "df_allele.rda"))
}


###############################################################################################################################################################################
# TO DELETE LATER
#library(readr)
#read_tsv("/gpfs/data/aifantislab/home/chrona01/analysis/numbat-main/results/lymphoma/P8814_merged/input/pileup_and_phase/P8814_DMSO_allele_counts.tsv.gz") -> P8814_DMSO
#read_tsv("/gpfs/data/aifantislab/home/chrona01/analysis/numbat-main/results/lymphoma/P8814_merged/input/pileup_and_phase/P8814_ROMI_allele_counts.tsv.gz") -> P8814_ROMI
#library(dplyr)
#df_allele <- bind_rows ("dmso" = P8814_DMSO, "romi" = P8814_ROMI, .id = "sample")
# print(df_allele[,c(1:5)])
#saveRDS(df_allele, file = "/gpfs/data/aifantislab/home/chrona01/analysis/numbat-main/results/lymphoma/P8814_merged/input/df_allele.rda")
#df_allele[1:10,1:10]
#df_allele2 <- df_allele%>%select(-sample, sample)
#df_allele2[1:10,1:10]
#P8814_merged <- data.frame(df_allele2)

##################################################################################################################
# Because this was from two Seurat obj I had to  merge the names in the cell+sample columns to match the names showing in the merged Seuerat obj
#P8814_merged$cell2 <- paste(P8814_merged$sample, P8814_merged$cell, sep="_")
#head(P8814_merged)

#names(P8814_merged)[names(P8814_merged) == 'cell-initial'] <- 'cellinitial'
#P8814_merged <- P8814_merged%>%select(-cellinitial, cellinitial)
#names(P8814_merged)[names(P8814_merged) == 'cell2'] <- 'cell'
#P8814_merged <- P8814_merged %>% select(cell, everything())

#saveRDS(P8814_merged, file = "/gpfs/data/aifantislab/home/chrona01/analysis/numbat-main/results/lymphoma/P8814_merged/input/df_allele-P8814_merged.rda")
###############################################################################################################################################################################